

export default function Privacy() {


    window.scrollTo({ top: 0, behavior: 'smooth', });

    return (



        <>

            <section className="max-w-screen-xl mx-auto px-4 gap-x-12 items-center justify-center lg:flex md:px-8 py-28 pb-0">

                <div className="p-8 w-full text-gray-800">
                    <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
                    <p className="text-sm text-gray-500">Last updated: October 31, 2024</p>

                    <p className="mt-6">
                        This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure
                        of Your information when You use the Service and tells You about Your privacy rights and how the
                        law protects You.
                    </p>
                    <p>
                        We use Your Personal data to provide and improve the Service. By using the Service, You agree to
                        the collection and use of information in accordance with this Privacy Policy.                      
                    </p>

                    <h2 className="text-2xl font-semibold mt-8 mb-4">Interpretation and Definitions</h2>

                    <h3 className="text-xl font-semibold mt-6">Interpretation</h3>
                    <p>
                        The words of which the initial letter is capitalized have meanings defined under the following
                        conditions. The following definitions shall have the same meaning regardless of whether they
                        appear in singular or in plural.
                    </p>

                    <h3 className="text-xl font-semibold mt-6">Definitions</h3>
                    <p>For the purposes of this Privacy Policy:</p>
                    <ul className="list-disc list-inside space-y-2 mt-4">
                        <li><strong>Account</strong>: a unique account created for You to access our Service or parts of our Service.</li>
                        <li><strong>Affiliate</strong>: an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                        <li><strong>Company</strong>: refers to NeoGrid, Mullanpara, Manjeri, Kerala, India.</li>
                        <li><strong>Cookies</strong>: small files placed on Your computer, mobile device, or any other device by a website, containing details of Your browsing history on that website among other uses.</li>
                        <li><strong>Country</strong>: Kerala, India.</li>
                        <li><strong>Device</strong>: any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
                        <li><strong>Personal Data</strong>: any information that relates to an identified or identifiable individual.</li>
                        <li><strong>Service</strong>: refers to the Website.</li>
                        <li><strong>Service Provider</strong>: any natural or legal person who processes the data on behalf of the Company.</li>
                        <li><strong>Third-party Social Media Service</strong>: any website or social network through which a User can log in or create an account to use the Service.</li>
                        <li><strong>Usage Data</strong>: data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., the duration of a page visit).</li>
                        <li><strong>Website</strong>: refers to <a href="http://www.neogrid.in/" target="_blank" rel="external nofollow noopener noreferrer" className="text-blue-500 underline">www.neogrid.in</a>.</li>
                        <li><strong>You</strong>: the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service.</li>
                    </ul>

                    <h2 className="text-2xl font-semibold mt-8 mb-4">Collecting and Using Your Personal Data</h2>

                    <h3 className="text-xl font-semibold mt-6">Types of Data Collected</h3>

                    <h4 className="text-lg font-medium mt-4">Personal Data</h4>
                    <p>
                        While using Our Service, We may ask You to provide Us with certain personally identifiable
                        information that can be used to contact or identify You. Personally identifiable information may
                        include, but is not limited to:
                    </p>
                    <ul className="list-disc list-inside space-y-2 mt-4">
                        <li>Email address</li>
                        <li>First name and last name</li>
                        <li>Phone number</li>
                        <li>Address, State, Province, ZIP/Postal code, City</li>
                        <li>Usage Data</li>
                    </ul>

                    <h4 className="text-lg font-medium mt-6">Usage Data</h4>
                    <p>
                        Usage Data is collected automatically when using the Service. It may include details such as Your
                        Device's IP address, browser type, pages of our Service that You visit, and other diagnostic data.
                    </p>

                    <h2 className="text-2xl font-semibold mt-8 mb-4">Use of Your Personal Data</h2>

                    <p>We may use Personal Data for the following purposes:</p>
                    <ul className="list-disc list-inside space-y-2 mt-4">
                        <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                        <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
                        <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
                        <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                        <li><strong>To provide You</strong> with news, special offers, and general information about other goods, services, and events which we offer.</li>
                        <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                    </ul>

                    <h2 className="text-2xl font-semibold mt-8 mb-4">Retention of Your Personal Data</h2>
                    <p>
                        The Company will retain Your Personal Data only for as long as is necessary for the purposes set
                        out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to
                        comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
                    </p>

                    <h2 className="text-2xl font-semibold mt-8 mb-4">Security of Your Personal Data</h2>
                    <p>
                        The security of Your Personal Data is important to Us, but remember that no method of transmission
                        over the Internet, or method of electronic storage is 100% secure.
                    </p>

                    <h2 className="text-2xl font-semibold mt-8 mb-4">Children's Privacy</h2>
                    <p>
                        Our Service does not address anyone under the age of 13. We do not knowingly collect personally
                        identifiable information from anyone under the age of 13. If You are a parent or guardian and You
                        are aware that Your child has provided Us with Personal Data, please contact Us.
                    </p>

                    <h2 className="text-2xl font-semibold mt-8 mb-4">Changes to This Privacy Policy</h2>
                    <p>
                        We may update Our Privacy Policy from time to time. We will notify You of any changes by posting
                        the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for
                        any changes.
                    </p>

                    <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
                    <p>
                        If you have any questions about this Privacy Policy, You can contact us by email at{' '}
                        <a href="mailto:info@neogrid.in" className="text-blue-500 underline">info@neogrid.in</a>.
                    </p>
                </div>

            </section>

        </>





    )





}
